base.webSite=http://live.smartlifein.com
base.upload.urlPrefix=http://live.smartlifein.com/static/upload/

email.account.expo.smtpServer=smtp.exmail.qq.com
email.account.expo.user=expo_notice@smartlifein.com
email.account.expo.password=45gwEmJfg
email.account.expo.accountName=\u667a\u6167\u751f\u6d3b\u7f51
email.account.expo.account=expo_notice@smartlifein.com

qcloud.secretId=xxx
qcloud.secretKey=xxx
qcloud.appId=xxx